-- MySQL Script generated by MySQL Workbench
-- 11/24/17 19:51:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sitioweb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sitioweb` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sitioweb` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Pagina` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoEvento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoEvento` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(20) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ciudad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ciudad` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Fecha` DATE NOT NULL,
  `Descripcion` VARCHAR(500) NULL,
  `IdSitioWeb` INT NOT NULL,
  `IdTipoEvento` INT NOT NULL,
  `IdCiudad` INT NOT NULL,
  `Ubicacion` VARCHAR(100) NULL,
  PRIMARY KEY (`Id`, `IdSitioWeb`, `IdTipoEvento`, `IdCiudad`),
  INDEX `fk_Eventos_Sitioweb1_idx` (`IdSitioWeb` ASC),
  INDEX `fk_Eventos_TipoEvento1_idx` (`IdTipoEvento` ASC),
  INDEX `fk_Eventos_Ciudad1_idx` (`IdCiudad` ASC),
  CONSTRAINT `fk_Eventos_Sitioweb1`
    FOREIGN KEY (`IdSitioWeb`)
    REFERENCES `mydb`.`Sitioweb` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_TipoEvento1`
    FOREIGN KEY (`IdTipoEvento`)
    REFERENCES `mydb`.`TipoEvento` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_Ciudad1`
    FOREIGN KEY (`IdCiudad`)
    REFERENCES `mydb`.`Ciudad` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellidos` VARCHAR(40) NOT NULL,
  `Usuario` VARCHAR(26) NOT NULL,
  `Password` VARCHAR(15) NOT NULL,
  `Correo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Favoritos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Favoritos` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(25) NULL,
  `IdUsuario` INT NOT NULL,
  `IdEventos` INT NOT NULL,
  PRIMARY KEY (`Id`, `IdUsuario`, `IdEventos`),
  INDEX `fk_Favoritos_Usuario_idx` (`IdUsuario` ASC),
  INDEX `fk_Favoritos_Eventos1_idx` (`IdEventos` ASC),
  CONSTRAINT `fk_Favoritos_Usuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `mydb`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favoritos_Eventos1`
    FOREIGN KEY (`IdEventos`)
    REFERENCES `mydb`.`Eventos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
